Add a `to_array_obj` method to Column
data-apis/dataframe-api pull request #163
Opened 2023-05-03 20:12 UTC by rgommers

Closes gh-139

2023-05-04 07:59 UTC, jorisvandenbossche commented on spec/API_specification/dataframe_api/column_object.py
> +        or device).
Is the expected behaviour that calling `to_array_obj()` already raises an error in case of an unsupported dtype?

2023-05-04 08:00 UTC, jorisvandenbossche commented
Should we specify the behaviour in case of nulls? (do some automatic conversion, or raise an error?) Or add a keyword that controls to which value it is converted?

2023-05-04 10:40 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +        or device).
Good point. I made this raise `TypeError`.

2023-05-04 10:40 UTC, rgommers commented
> Should we specify the behaviour in case of nulls? (do some automatic conversion, or raise an error?) Or add a keyword that controls to which value it is converted?

Good question - I added a keyword and specified `ValueError` when `null`s cause a column to not be convertible.

2023-05-04 15:08 UTC, jorisvandenbossche commented on spec/API_specification/dataframe_api/column_object.py
> +            - ``to-nan``: for floating-point dtypes, convert any nulls to ``nan``.
This _could_ be generalized to apply to any numeric type, instead of only floating points (i.e. allowing to convert ints with nulls to float with nans)

2023-05-04 15:38 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +            - ``to-nan``: for floating-point dtypes, convert any nulls to ``nan``.
True. I'm not sure how desirable that is, it may be pragmatic in the absence of a good alternative. Let's see what others think about this.

2023-05-04 17:05 UTC, MarcoGorelli requested changes
Thanks for doing this

My only request would be to force the target dtype to be specified (to prevent implementers from stuffing everything into an object ndarray - looking at you, pandas nullable dtypes)

2023-05-04 17:23 UTC, rgommers commented
> My only request would be to force the target dtype to be specified

That would be counterproductive I think. The intended usage is this:
```python
# If you want say a PyTorch tensor, replace `np.asarray` with `torch.Tensor`:
np.asarray(col.to_array_obj())
```
In, e.g., Matplotlib that is supposed to work for pretty much any dtype. How would you usefully fill in a `dtype=` keyword here?

>  (to prevent implementers from stuffing everything into an object ndarray - looking at you, pandas nullable dtypes)

That is a mis-feature in pandas, and it should be solved in pandas imho. This standard nor any other array library even has the concept of an object array.

If it would help to address this specific concern, I'd rather specify something like "a dataframe library must produce the closest matching dtype of the array library in case it produces an array type instance itself (e.g. _"a column with a floating-point dtype must produce the corresponding floating-point dtype of the same precision that the array library offers"_.

2023-05-04 17:25 UTC, MarcoGorelli commented
> I'd rather specify something like "a dataframe library must produce the closest matching dtype of the array library in case it produces an array type instance itself (e.g. "a column with a floating-point dtype must produce the corresponding floating-point dtype of the same precision that the array library offers".

sure, sounds good, that makes it clear that pandas' nullable dtypes `to_numpy` default behaviour is considered non-compliant

2023-05-05 06:59 UTC, jorisvandenbossche commented
Yes, see also what Ralf already added about nulls causing a ValueError. Most of the cases that pandas currently gives object dtype would already give an error for that reason.

2023-05-05 11:40 UTC, MarcoGorelli approved these changes
This is fine actually, apologies, it already says

> of a library implementing the array API standard

which excludes the object dtype anyway

Looks good to me, thanks!

2023-05-10 12:23 UTC, MarcoGorelli commented
Looks good - OK to merge?

2023-05-10 20:03 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +            - ``to-nan``: for floating-point dtypes, convert any nulls to ``nan``.
This option could also be removed completely, assuming we add `fill_null(scalar_value)`, in favor of a separate `col.fill_null(float('nan')).to_array_obj()`.

2023-05-10 20:03 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +            - ``to-nan``: for floating-point dtypes, convert any nulls to ``nan``.
Syntax-wise, keeping `'to-nan'` is probably nicer though.

2023-05-10 20:05 UTC, rgommers commented
> Looks good - OK to merge?

I added the language regarding the "may produce object dtype" concern, and am now happy with this PR. There is one open point on what to do with `null_handling='to-nan'` - I don't have a strong preference there. We could discuss over the next day and merge then if everyone is happy.

2023-05-11 03:47 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +        Obtain an object that can be used as input to ``asarray`` or ``from_dlpack``
Mostly, yes. The main pain point there is that the array API standard doesn't mandate that `asarray` has to support DLPack. There was a desire to keep that orthogonal (long discussion, and I believe you were involved in that). So now if we have a column with a dtype which can support DLPack, that will work with `numpy.asarray` but not necessarily with other libraries.

2023-05-11 03:48 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +        Obtain an object that can be used as input to ``asarray`` or ``from_dlpack``
So we can just drop `from_dlpack` from the description and leave everything else unchanged.

2023-05-11 03:51 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +          in a library of interest
> Is the goal of this function to work generally with multiple libraries `asarray` implementations or just a specific library's implementation?

I'd say neither is 100% accurate. It's more the former, however it does make sense to add library-specific methods - and in fact, `__array__` is one already. There is no single interchange method that is supported by all libraries' `asarray` function anyway, nor is that a good goal because it would eliminate support for dtypes like string and datetime which numpy supports and some other array library could support, but most libraries never will.

2023-05-11 17:08 UTC, amueller commented on spec/API_specification/dataframe_api/column_object.py
>      constructor functions or an already-created dataframe object retrieved via
Not related to the PR bu the sentence seems to be missing something?

2023-05-12 19:23 UTC, kkraus14 commented on spec/API_specification/dataframe_api/column_object.py
> +          in a library of interest
I guess my fear is that say some dataframe library `fancy_dataframe` could expect to work downstream with `fancy_array` and return something that supports `__fancy_array__` which `fancy_array.asarray` handles, but a developer calls `np.asarray` against the output of this and it understandably doesn't work.

2023-05-13 10:32 UTC, rgommers commented on spec/API_specification/dataframe_api/column_object.py
> +          in a library of interest
I don't think that fear is justified, because:
- this method already allows returning an instance of `fancy_array` directly anyway,
- the returned object should have other, more standard methods too if possible, so `np.asarray` can still work
- if there's something really specific in the column such that it's not possible to add anything but `__fancy_array__` anway, then nothing is lost by doing so

2023-05-25 18:07 UTC, MarcoGorelli requested changes
A suggestion which came out of today's call was to not have `to_array_obj` in the end, but to instead have `Column.column`. And put a big warning in its docs, telling users that if they invoke it, then they are leaving the Standard territory and that we make no guarantees about what will or won't work with it

I'd prefer that TBH. Any objections?

(requesting changes so this doesn't get accidentally merged before we've figured it out)

2023-05-25 18:44 UTC, jorisvandenbossche commented
Some other options to consider:

- Give up on trying to be array-library agnostic, and just add an explicit `to_numpy()` so at least we have something that is dataframe-library-independent to get a numpy array.
- Limit ourselves to numeric data types for now, so we could specify that the returned object from `to_array_obj()` needs to have `__dlpack__`, to make this a more well defined specification

2023-05-25 20:20 UTC, kkraus14 commented
I think the challenge is that the API as it currently exists is too ambiguous and encourages use as opposed to it being an "escape hatch". I think what we generally agreed on the call today was:

- There's desire for an API to return an array that guarantees you can use the array API against it, but doesn't make any guarantees about memory layout
- There's desire for an API to return something that guarantees `__dlpack__` interchange compatibility
- These two shouldn't be the same API
- There's going to need to be an escape hatch to use library specific functionality that is not standardized and this `to_array_obj` is just a single instance of that. We provide an escape hatch at the DataFrame level today via the `.dataframe` property: https://github.com/data-apis/dataframe-api/blob/main/spec/API_specification/dataframe_api/dataframe_object.py#L83-L90. Providing an equivalent of that at the Column level serves the purpose of `to_array_obj` as well as serving the purpose of future cases where there's desire to break away from the standard.

2023-06-22 14:05 UTC, MarcoGorelli commented
I noticed that plotly have this:

https://github.com/plotly/plotly.py/blob/4ab63db64b09d7e8ba28ea2eb67fbefe7c18ffd4/packages/python/plotly/_plotly_utils/basevalidators.py#L169-L174

in case it's `False`, then the iterate over the elements 1 by 1

----

If we can find closure to this discussion, then that's probably everything that plotly would need to be DataFrame-agnostic (from my initial experimentation at least)

plotly's dataframe handling is _way_ simpler than seaborn's, so they might be a better target for now (they've also expressed interest)

2023-06-22 15:30 UTC, kkraus14 commented
> I noticed that plotly have this:
> 
> https://github.com/plotly/plotly.py/blob/4ab63db64b09d7e8ba28ea2eb67fbefe7c18ffd4/packages/python/plotly/_plotly_utils/basevalidators.py#L169-L174
> 
> in case it's `False`, then the iterate over the elements 1 by 1

The link here 404s, any chance you could update it?

2023-06-22 16:53 UTC, MarcoGorelli commented
thanks @kkraus14 , have fixed

2023-08-01 12:50 UTC, MarcoGorelli commented
superseded by #209 - closing then, thanks all for the discussion

2023-08-01 12:50 UTC, closed without merging