Declare enums explicitly, fix type hints
data-apis/dataframe-api pull request #74
Opened 2022-02-10 17:46 UTC by vnlitvinov

Signed-off-by: Vasily Litvinov <vasilij.n.litvinov@intel.com>

This is related to #73

2022-02-23 13:58 UTC, rgommers reviewed
Overall LGTM, thanks @vnlitvinov. Just one question about `ColumnNullType`

2022-02-23 13:58 UTC, rgommers commented on protocol/dataframe_protocol.py
> +class ColumnNullType:
Shouldn't this inherit from `enum.IntEnum` too? It was a plain `int` before, but if the type is changed then may as well?

2022-02-23 13:58 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def describe_categorical(self) -> Dict[bool, bool, Optional[dict]]:
This was kind of on purpose (https://www.python.org/dev/peps/pep-0585/). Okay to change to support older Python versions, we're just going to have to change it back then at some point.

2022-02-24 07:57 UTC, vnlitvinov commented
I'm converting this to draft until I finish migrating the prototype to pandas - I've already had to change a few things here...

2022-02-25 14:40 UTC, rgommers commented
Thanks @vnlitvinov!

> 2\. `Column.describe_categories` is now raising `TypeError` on non-categorical dtypes instead of `RuntimeError`

This seems fine to me.

> 1. `Column.describe_categories` now returns a tuple of three elements (aligning the spec with what all existing implementations do). This keeps things in sync, but hardens future extensions - so we should discuss that.

These are the implementations:

- https://github.com/vaexio/vaex/blob/d5410f84c1c5d09a82b50c7624aa7e079b60dde1/packages/vaex-core/vaex/dataframe_protocol.py#L415
- https://github.com/rapidsai/cudf/pull/9071/files#diff-767b6167ce820d12d6181ce4681e393dc15db89906b4fba8f66747ba901e7469R263

The docstrings also talk about a dictionary in both places; for cuDF the type annotation matches the code (tuple), in Vaex it matches the docs.

I think we're fine making backwards incompatible changes at this point. So I'd vote for using a dictionary, it's not much more verbose, and makes it possible to add another return value in case that would ever be needed. @maartenbreddels, @shwina what do you think?

2022-02-25 14:53 UTC, rgommers commented
> 3\. `DataFrame.__dataframe__` was removed (it was confusing), it's `version` field was moved to `DataFrame.version` attribute instead

This was inherited from:
- https://github.com/data-apis/dataframe-api/issues/29#issuecomment-685123386. 
- https://github.com/wesm/dataframe-protocol/pull/1/files#diff-795b2df2ad93d3228f75df701bd639970c54ee8232bb8f99540ea6d2aa435018R198

Both of those define this, and it kinda makes sense to have it. There was discussion elsewhere too that I cannot find right now. 

The rationale for removing it is unclear, and you are also removing docs and keywords that are needed. Can you please explain in more detail why you want to do this @vnlitvinov?

2022-02-25 16:51 UTC, vnlitvinov commented
The comment you're linking at describes something which is somewhat different from what we have now in the spec.
That `cuDFFrame.__dataframe__` method was describing the internals to some extent, while the implementation I removed returned `self` and `version`.

My main point is `__dataframe__` should belong to a _real_ dataframe object, not to an exchange one, serving as a distinction flag if you wish.

Alternatives to removing the method on _exchange object_ are:
* change the signature of this `__dataframe__` to always return `self` and keep `.version` as class attribute, but, to be honest, I don't see much value in that;
* change the spec of `.__dataframe__` method on a _real_ dataframe object to return a dictionary instead.

I am personally inclined to just remove the method on the exchange object, but I'm curios what others think (cc @jorisvandenbossche @shwina @jreback @aregm)

2022-03-16 17:24 UTC, rgommers commented
> My main point is `__dataframe__` should belong to a _real_ dataframe object, not to an exchange one, serving as a distinction flag if you wish.

I reviewed this again:
- you are right that the current implementation returning a dict of `self` and `version` isn't good.
- Vaex left it out: https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/dataframe_protocol.py#L678
- cuDF also left it out: https://github.com/rapidsai/cudf/blob/aa746ae3d2035809c516ab6a2100e4336e1cfa21/python/cudf/cudf/core/df_protocol.py#L504

I think `return self` would still make sense, and not having `__dataframe__` isn't distinguishing of this being a protocol-conforming object, but I'm fine with merging this as is.

> change the signature of this `__dataframe__` to always return `self` and keep `.version` as class attribute, but, to be honest, I don't see much value in that;

The point of this would be that if you want code that handles a mix of dataframe types/objects, the only guarantee you have that if you call `df.__dataframe__` you get a protocol-conforming object (if it exists of course). There's no other robust `isinstance` check you can do. But it only matters if people are going to be passing around these objects to begin with. 

> Oh, forgot to add... as for changing the `.describe_categorical` - should we turn other description fields (`.decribe_null` and `.dytpe`) into `dicts` instead in the sake of better extensibility?

Not sure about that, that'd be quite verbose and quite a bit of churn. Given that we'd have to version the protocol to do anything with it, and can deal with a backwards-compatible extension via versioning, I'd suggest to leave it as is.

2022-03-16 17:29 UTC, rgommers requested changes
Reviewed again, all looks fine except for my one comment about not deleting docs and the `_nan_as_null` and `_allow_copy` attributes.

2022-03-16 17:29 UTC, rgommers commented on protocol/dataframe_protocol.py
> -                      allow_copy : bool = True) -> dict:
Can you change this to `__init__` (as in https://github.com/rapidsai/cudf/blob/aa746ae3d2035809c516ab6a2100e4336e1cfa21/python/cudf/cudf/core/df_protocol.py#L514) instead of throwing these docs and `_nan_as_null` and `_allow_copy` attributes away?

2022-04-02 19:48 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
The reason this may be `None` is that the size may be unknown, or expensive to calculate. IIRC there was a fair bit of discussion about this, and this was on purpose. Same as `null_count` further down.

2022-04-02 19:49 UTC, rgommers commented
Thanks @vnlitvinov. LGTM modulo my one comment.

2022-04-04 14:57 UTC, YarShev commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
@rgommers, could you elaborate when the size could be unknow? Also, if the size is expensive to calculate, why should we return `None`?

2022-04-05 08:15 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
Think of a library using delayed evaluation of method calls that can give a variable size (filter/select/etc.). Accessing `.size` will trigger immediate evaluation, which can take an arbitrary amount of time. Dask is an example of such a library.

And why: a property lookup is supposed to be fast, and not trigger expensive computations. If so, it should be converted to a method. But `.size` is well-established, and the preference was for this property to remain but for libraries to allow returning `None` if the size is unknown without triggering a computation.

2022-04-05 09:11 UTC, YarShev commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
What if the user eventually wants to get the size of a column? Does the user have to use a different/extra API to get it?

2022-04-05 13:34 UTC, vnlitvinov commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
Also note that `Buffer` has `.bufsize` which is _somewhat_ equal to this size computing.
Hence maybe we should introduce some separate method of getting the size?

2022-04-13 12:49 UTC, vnlitvinov commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
@rgommers ping on the questions above?

2022-05-04 12:21 UTC, vnlitvinov commented
Note: this PR is aiming to change the spec, so https://github.com/data-apis/dataframe-api/pull/69 is also related.

2022-07-07 12:11 UTC, vnlitvinov commented
I would say it's blocked by #69, let's merge that and then update this and merge it as well.

2022-07-07 15:07 UTC, vnlitvinov commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
buffers themselves don't have dtypes, but _the data_ which is contained within a buffer does have it

2022-07-07 15:08 UTC, vnlitvinov commented on protocol/dataframe_protocol.py
> +        Use explicit float NaN/NaT value.
I don't have much insight here, was just moving the enum descriptions from `.describe_null` docstring. @rgommers might know more about that.

2022-07-07 15:12 UTC, kkraus14 commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
Could I not have two columns that share a data buffer with 64 bytes, where column1 is of type int8 with 64 elements, and column2 is of type int32 with 16 elements?

2022-07-14 15:59 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
@kkraus14 is correct here I think, the decision was that buffers are just memory, and the interpretation of that is done at the column level.

2022-07-14 16:01 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
We decided here that `None` (and hence `Optional`) can indeed be dropped. So the current change here is fine. 

Let me point out that we then indeed change `.size` from a _property_ to a _method_. I'll not resolve this issue yet to give folks a chance to respond.

2022-07-14 16:09 UTC, rgommers commented on protocol/dataframe_protocol.py
> +        Use explicit float NaN/NaT value.
`USE_NAN` is just for floating point data then. `NaT` should be removed here.

In the `USE_SENTINEL` value it should be usable - it's just a particular value of the same data type as the rest of the data in the column, which is always understandable by the receiving library I'd say. So it can stay there.

2022-07-14 18:39 UTC, jorisvandenbossche commented on protocol/dataframe_protocol.py
> +        Use explicit float NaN/NaT value.
The pandas implementation would also need to be updated (it currently uses `USE_NAN` for datetime data):

https://github.com/pandas-dev/pandas/blob/a7b8c1dc8cf76ab36e45315386a1a9d8274a8974/pandas/core/exchange/column.py#L41

2022-07-28 10:07 UTC, rgommers commented on protocol/dataframe_protocol.py
> +        The byte is set/unset representing a null on a certain position.
I believe we went with the Arrow convention, and that is why the buffer is called `validity` (where it's clear that `1` is valid/non-masked data) rather than the more ambiguous "mask".

2022-07-28 12:26 UTC, rgommers commented on protocol/dataframe_protocol.py
> +        Use explicit float NaN/NaT value.
I pushed a commit removing `NaT`.

2022-07-28 12:28 UTC, rgommers commented
I pushed a rebase after fixing conflicts introduced after merging gh-69 (in `describe_categorical`, and also updated the related `CategoricalDescription`).

2022-07-28 13:09 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
> Let me point out that we then indeed change `.size` from a _property_ to a _method_. I'll not resolve this issue yet to give folks a chance to respond.

Which is not what this PR does right now, this declares a _property_ in an ABC:
```
@property
@abstractmethod
```
Going from `.size` to `.size()` would be a pretty annoying bc-breaking change at this point (goes for `null_count` as well).

2022-07-28 13:16 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
Actually, you are both correct. At the `Buffer` level there is no dtype indeed (as @kkraus14 said), however this is the static typing for the dict returned by a method on `Column` - at which point you do indeed know what the interpretation of the buffer is for this particular column (as @vnlitvinov points out).

I think we can resolve this comment.

2022-07-28 13:22 UTC, rgommers commented on protocol/dataframe_protocol.py
> +        The byte is set/unset representing a null on a certain position.
Actually no, after digging in more: we have `Column.describe_null` which says "return the missing value representation". So both numpy-style and arrow-style can be represented there. This answer would be more obvious if the type annotation would be right next to the doctring of the property. But that is what it is. The current docstring is clear I'd say, so I'll resolve this comment.

2022-07-28 17:48 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
Re-discussed once more (apologies for the churn): consensus was to turn these into methods indeed, to indicate that they may trigger a potentially expensive computation to return the size as an integer.

2022-07-29 13:27 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    def size(self) -> int:
Pushed a commit to turn `.size` into a method (with an explanation in its docstring). 

`null_count` remains `Optional[int]`, so I did not touch it.

2022-07-29 13:30 UTC, rgommers approved these changes
All comments have been resolved now, so I will merge this. Thanks a lot @vnlitvinov and everyone else who commented.

Between this PR and gh-69, there are now two bc-breaking changes. We've agreed that those changes will be synced quickly to Pandas (by @mroeschke), Vaex (by @honno), Modin by (@vnlitvinov) and cuDF (by @shwina), so that won't give problems with implementations that are not in sync with each other.

2022-07-29 13:32 UTC, merged

2022-08-02 08:18 UTC, jorisvandenbossche commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
One further question here: if the Buffer itself has no dtype (this information is only at the Column level), doesn't that conflict with the `__dlpack__` method being on the Buffer? (as far as I know a dlpack tensor does have a dtype?)

2022-08-02 09:32 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
Good question. I am not 100% sure (and either way we should document it in more detail), but I think the answer is that this is still useful in principle, since the caller has access to the interpretation of the raw bytes at the column level. Even in the case of @kkraus14's example where one buffer backs two columns with different dtypes, `__dlpack__` can be used to exchange the raw data and it doesn't really matter what data type it uses; it can always be reinterpreted with the column-level dtype info.

On the other hand, `__dlpack__` at the column level won't work at all for exchanging data in several cases. E.g., datetime64 and string dtypes, or when there's a separate validity buffer. 

The Pandas implementation looks fine to me: https://github.com/pandas-dev/pandas/blob/3ad429e616fd7fcb796a62149ab0d94d8d9d3353/pandas/core/interchange/buffer.py#L52-L58

2022-08-02 10:46 UTC, jorisvandenbossche commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
Side question: for dlpack, in case of a Buffer for a Datetime column, it could also return an int64 tensor? (right now the pandas implementation will error, since it falls back to numpy's method, and the array we store is a datetime64 array which doesn't support dlpack)

2022-08-02 13:05 UTC, rgommers commented on protocol/dataframe_protocol.py
> +    # second element is the data buffer's associated dtype
Yes, I think that is a valid thing to do. Even in plain numpy you can deal with the underlying `int64` in memory in a well-defined way:
```python
>>> x = np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')
>>> x.dtype
dtype('<M8[D]')
>>> x.strides
(8,)
>>> x.view(np.int64)
array([13707, 13161, 14834])
>>> x.view(np.int64)[0] = 1300
>>> x
array(['1973-07-24', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')
```

2022-08-04 10:17 UTC, vnlitvinov commented
Pull request for syncing Modin with new spec: https://github.com/modin-project/modin/pull/4763

2022-08-08 19:15 UTC, honno commented
vaex PR for syncing with new spec https://github.com/vaexio/vaex/pull/2150

2022-08-08 20:51 UTC, mroeschke commented
pandas PR for syncing with new spec

https://github.com/pandas-dev/pandas/pull/47887
https://github.com/pandas-dev/pandas/pull/47886

2022-08-10 08:23 UTC, vnlitvinov commented
Follow-up question - `Column.describe_categorical` among others returns `is_dictionary: bool` element and `categories: Column` (the latter could be `None`). Is `is_dictionary` still valid and is it even needed if `categories` can just be `None` to signify the same meaning that we cannot convey the categories?..

cc @rgommers @shwina @mroeschke @honno

2022-08-10 08:31 UTC, honno commented
> Is `is_dictionary` still valid and is it even needed if `categories` can just be `None` to signify the same meaning that we cannot convey the categories?

In terms of necessity in interchange, I don't think so, as yeah you can just go `col.describe_categorical["categories"] is None`. Now you mention it, in terms of semantics IMO I'd prefer checking for `None` over checking a separate variable.